server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LittleStone8/spring-cloud-config-repo    # 配置Git仓库的地址
          username: 262627160@qq.com                                                          # Git仓库的账号
          password: huang#392127                                                       # Git仓库的密码