server:
  port: 8761                    # 指定该Eureka实例的端口
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LittleStone8/spring-cloud-config-repo    # 配置Git仓库的地址
          username: 262627160@qq.com                                                          # Git仓库的账号
          password: huang#392127                                                       # Git仓库的密码
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    microservice-helloword: /www/**

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756